apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp-deployment
  namespace: default
  labels:
    app: loginapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - name: loginapp-container
        image: omkarok/javac:loginapp
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: default
