apiVersion: v1
kind: Service
metadata:
  name: loginapp-service
  namespace: default
spec:
  selector:
    app: loginapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
